### ISSUE TITLE
add license

### ISSUE THREAD

**Issue by SkyBulk** [zhenya-paitash/app-ecommerce-2023#1]
it's a very interesting project!

Would you consider adding a license to this repository to specify under which terms this code can be used?

**Comment by zhenya-paitash** [comment]
@SkyBulk Thank you for your feedback 
I have already [corrected it ](https://github.com/zhenya-paitash/app-ecommerce-2023/commit/5a4809fed89870913af2582011412180c7b7aba5)by adding the MIT License
